services:
  db-productos:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: productos_db
    ports:
      - "3306:3306"

  api-productos:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db-productos